version: "2"
volumes:
  sqlite:
services:

  greenmail:
    image: greenmail/standalone
    ports:
# - smtp  : 3025
      - "25:3025"
# - smtps : 3465
#      - "3465:3465"
# - pop3  : 3110
#      - "3110:3110"
# - pop3s : 3995
#      - "3995:3995"
# - imap  : 3143
      - "143:3143"
# - imaps : 3993
#      - "3993:3993"

  webmail:
    build: webmail/
    image: inetsoftware/roundcube
    environment:
      - IMAP_HOSTNAME=greenmail
      - IMAP_PORT=3143
      - SMTP_HOSTNAME=greenmail
      - SMTP_PORT=3025
    ports:
      - "8080:80"
    volumes:
      - sqlite:/var/lib/dbconfig-common/sqlite3/roundcube
